### ISSUE TITLE
Enquiry on the method in amplifying the voltage in 'Booster_Board'

### ISSUE THREAD

**Issue by YuseopSim** [ZJUNlict/Booster_Board#1]
I trully appreciate on what you guys are sharing this awesome works here.
Currently I am working on some project that need the implementation of this booster board, which I am trying to study on your contribution here, but I wonder about some issue about your circuit.
For charging a 200V capacitor, it seems to have amplify certain element somewhere( to increase almost 190V)
but I could not find that how make it.
If you mind.. please give me a clue for several issues.
1. How much voltage came on 'Battery_in' node
2. How did you make amplifing that voltage
3. in communication protocol, it contain 7bits for shoot(or chip) impact control.
Then, on your circuit, how did you implement on your circuit for it works.
Take care,
Shim

**Comment by icly** [comment]
Thank you for using our design as a reference. I'll explain the issues you have in the following. 
1. The voltage at the ‘Battery_in' node is the direct input from a 4S1P LiPo Battery which is about 15V to 16.8V. The voltage can be changed as long as the UC3843 ic can work properly for the charging circuit.
2. The principle used is called boost converter. https://en.wikipedia.org/wiki/Boost_converter
3. In the communication protocol, the 7bits represent the shoot/chip power. It is controlled by the discharge time using the MOSFET. In the mainboard, the MCU will generate high-level signals with different pulse widths to a pre-driver and then drive the MOSFET to discharge.
If you have further questions, just post it here. 
Best regards,
Lingyun
